services:
  postgres:
    image: postgres:16
    container_name: wb-platform-db
    environment:
      POSTGRES_USER: wb
      POSTGRES_PASSWORD: wb
      POSTGRES_DB: wb_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
